#!/usr/bin/env python3
"""Regenerate stars-data.js from stars.png.

The browser cannot read pixels from a file:// image (Firefox/Chrome treat each
file as a unique origin, which taints the canvas and makes getImageData throw),
so the star geometry is baked into a JS file at build time instead.

Re-run this after editing stars.png:
    python3 tools/gen-stars-data.py
"""
import pathlib
import sys

from PIL import Image
import numpy as np

# Pixels at or above this alpha count as part of a star. Kept here only: the
# runtime in stars.js receives the baked centroids and never re-thresholds, so
# these two values are build-time settings with no JS counterpart to match.
ALPHA_FLOOR = 24
MIN_PIXELS = 4

ROOT = pathlib.Path(__file__).resolve().parent.parent


def cluster(stars_alpha, width, height):
    """8-connected flood fill, mirroring extractStars() in stars.js."""
    solid = [a >= ALPHA_FLOOR for a in stars_alpha]
    seen = bytearray(width * height)
    out = []
    for seed in range(width * height):
        if not solid[seed] or seen[seed]:
            continue
        stack = [seed]
        seen[seed] = 1
        sx = sy = peak = count = 0
        min_x, max_x, min_y, max_y = width, -1, height, -1
        while stack:
            idx = stack.pop()
            x = idx % width
            y = idx // width
            a = stars_alpha[idx]
            sx += x
            sy += y
            count += 1
            if a > peak:
                peak = a
            min_x, max_x = min(min_x, x), max(max_x, x)
            min_y, max_y = min(min_y, y), max(max_y, y)
            for dy in (-1, 0, 1):
                ny = y + dy
                if ny < 0 or ny >= height:
                    continue
                for dx in (-1, 0, 1):
                    if not dx and not dy:
                        continue
                    nx = x + dx
                    if nx < 0 or nx >= width:
                        continue
                    n = ny * width + nx
                    if solid[n] and not seen[n]:
                        seen[n] = 1
                        stack.append(n)
        if count < MIN_PIXELS:
            continue
        span = max(max_x - min_x + 1, max_y - min_y + 1)
        out.append((round(sx / count), round(sy / count), span, peak))
    return out


def main():
    src = ROOT / 'stars.png'
    if not src.exists():
        sys.exit(f'missing {src}')
    im = Image.open(src).convert('RGBA')
    w, h = im.size
    alpha = np.asarray(im.getchannel('A')).ravel().tolist()
    stars = cluster(alpha, w, h)
    stars.sort(key=lambda s: (s[1], s[0]))

    body = ','.join(f'[{x},{y},{sp},{pk}]' for x, y, sp, pk in stars)
    js = (
        '// Generated by tools/gen-stars-data.py from stars.png - do not edit by hand.\n'
        f'// Each entry: [centreX, centreY, spanPx, peakAlpha] in image pixel space.\n'
        f'window.STAR_FIELD = {{ w: {w}, h: {h}, stars: [\n{body}\n] }};\n'
    )
    dest = ROOT / 'stars-data.js'
    dest.write_text(js)
    print(f'{len(stars)} stars -> {dest.name} ({dest.stat().st_size} bytes)')


if __name__ == '__main__':
    main()
